name: covoiturage_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

  # ğŸ”¹ Core project dependencies
  http: ^0.13.6
  animations: ^2.1.0
  flutter_staggered_animations: ^1.1.1

  # ğŸ”¹ Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10

  # ğŸ”¹ Google services
  google_maps_flutter: ^2.13.1
  google_maps_webservice: ^0.0.19
  google_sign_in: ^6.2.1

  # ğŸ”¹ Location / Map
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  geolocator: ^14.0.2

  # ğŸ”¹ Miscellaneous utilities
  url_launcher: ^6.3.1
  mailer: ^6.6.0
  table_calendar: ^3.1.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bus.png
    - assets/images/car.png
    - assets/google_logo.svg
